### ISSUE TITLE
bot crash 

### ISSUE THREAD

**Issue by ch4oz4ngel** [tama/pogo-discord-mod-bot#39]
it crash after 1 minute

(bot-env) root@59997-53573:/home/pogo-discord-mod-bot/mod_bot# python3 main.py
reading configuration
on_ready
{}
Traceback (most recent call last):
  File "main.py", line 443, in <module>
    loop.run_until_complete(asyncio.gather(run(token), modtask()))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "main.py", line 296, in modtask
    warn_interval = int(get(server.id, "mod.warn_interval", conf))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by tama** [comment]
Try to edit your config.json file with this one :

[config.zip](https://github.com/tama/pogo-discord-mod-bot/files/5012324/config.zip)

It is a very basic configuration file, so some functions will need more tweaking to work, but it should solve the crash.

**Comment by ch4oz4ngel** [comment]
self problem

config edit with  following

{
    "raid_duration": 45,
    "mod": {
        "roles": "mod",
        "delete_interval_after_warning": 5,
        "warn_interval": 15
    },
  "filepath": "/home/pogo-discord-mod-bot",
  "listen_to" : {648220935375290370
  }
}

**Comment by ch4oz4ngel** [comment]
same with 

(bot-env) root@59997-53573:/home/pogo-discord-mod-bot# cat config.json
{
    "raid_duration": 45,
    "mod": {
        "roles": "mod",
        "delete_interval_after_warning": 5,
        "warn_interval": 15
    },
  "filepath": "/home/pogo-discord-mod-bot",
  "listen_to" : {
    "648220935375290370": {
      "id": "Allgemein",
      "channel": "648220935823949856"
                          }
                }
}

**Comment by tama** [comment]
> it crash after 1 minute
> 
> (bot-env) root@59997-53573:/home/pogo-discord-mod-bot/mod_bot# python3 main.py
> reading configuration
> on_ready
> {}

The last line shows that it didn't read the configuration correctly, make sure the config.json file is in the same directory as your main.py file, and is a valid json.

**Comment by ch4oz4ngel** [comment]
what i must do that the bot start without locale
i only want start raid but without any coordination to meet
its only for raids far away

**Comment by tama** [comment]
What do you mean, "without locale" ?

**Comment by ch4oz4ngel** [comment]
you programmed the bot with lin and len for paris 
i dont need locations 
in pogo you can invite with faraway tickets all over the world

**Comment by tama** [comment]
Hm no, I did not. The gym locations are in the gym_with_coords file.
If you don't need it, you probably don't need mod-bot, raid-bot alone should be enough, though you'll need to "summon" it in each channel before being able to use its features :
`@raid-bot !summon`

**Comment by ch4oz4ngel** [comment]
ok then i have to give a new problem report because the raid bot just doesn't respond to commands unfortunately he recognizes all messages but does not react

**Comment by tama** [comment]
Are you talking about this bot, or the raid bot ? If it is the latter, please open an issue in the corresponding project (pogo-discord-raid-bot), with a log/stacktrace of what's happening when you send a recognized command.
Also, is the problem ("bot crash") solved ? If so, I'll close this issue.

**Comment by ch4oz4ngel** [comment]
This is solved yes
